// POKEMON types
export const ADD_POKEMON = 'ADD_POKEMON';
export const DELETE_POKEMON = 'DELETE_POKEMON';
export const SET_SELECTED_POKEMON = 'SET_SELECTED_POKEMON';
export const GET_POKEMONS = 'GET_POKEMONS';
export const UPDATE_POKEMON = 'UPDATE_POKEMON';
export const CLEAR_INSERTED_POKEMON = 'CLEAR_INSERTED_POKEMON';

// LEAGUE types
export const ADD_LEAGUE = 'ADD_LEAGUE';
export const DELETE_LEAGUE = 'DELETE_LEAGUE';
export const SET_SELECTED_LEAGUE = 'SET_SELECTED_LEAGUE';
export const GET_LEAGUES = 'GET_LEAGUES';
export const UPDATE_LEAGUE = 'UPDATE_LEAGUE';
export const CLEAR_INSERTED_LEAGUE = 'CLEAR_INSERTED_LEAGUE';
