// POKEMON types
export const ADD_POKEMON = 'ADD_POKEMON';
export const DELETE_POKEMON = 'DELETE_POKEMON';
export const GET_POKEMON = 'GET_POKEMON';
export const GET_POKEMONS = 'GET_POKEMONS';
export const UPDATE_POKEMON = 'UPDATE_POKEMON';
export const FILTER_POKEMONS = 'FILTER_POKEMONS';
export const CLEAR_INSERTED_POKEMON = 'CLEAR_INSERTED_POKEMON';
